{{- if .Values.llm.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llm-platform.fullname" . }}-secret
  labels:
    {{- include "llm-platform.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.llm.apiKey | b64enc }}
{{- end }}

