apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: tenant-{{TENANT}}
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["10.244.0.0/16"]
    services:
      cidrBlocks: ["10.96.0.0/12"]
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: tenant-{{TENANT}}-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: tenant-{{TENANT}}-docker
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  name: tenant-{{TENANT}}-docker
  namespace: default
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: tenant-{{TENANT}}-control-plane
  namespace: default
spec:
  replicas: 1
  version: v1.30.0
  kubeadmConfigSpec:
    clusterConfiguration:
      controllerManager: {}
      scheduler: {}
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "role=control-plane"
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: DockerMachineTemplate
      name: tenant-{{TENANT}}-control-plane
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: tenant-{{TENANT}}-control-plane
  namespace: default
spec:
  template:
    spec: {}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: tenant-{{TENANT}}-md-0
  namespace: default
spec:
  clusterName: tenant-{{TENANT}}
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: tenant-{{TENANT}}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: tenant-{{TENANT}}
    spec:
      clusterName: tenant-{{TENANT}}
      version: v1.30.0
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: tenant-{{TENANT}}-md-0
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: tenant-{{TENANT}}-md-0
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: tenant-{{TENANT}}-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "role=worker"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: tenant-{{TENANT}}-md-0
  namespace: default
spec:
  template:
    spec: {}
